# Generated by Django 4.1 on 2022-08-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seats', '0002_hall_seat_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='movie_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='hall',
            name='movie_time',
            field=models.TimeField(null=True),
        ),
    ]
