# Generated by Django 4.1 on 2022-08-15 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('seats', '0004_hall_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookedseats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_date', models.DateField(null=True)),
                ('movie_time', models.TimeField(null=True)),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('booked_time', models.TimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
        migrations.RemoveField(
            model_name='seat',
            name='hall',
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=200),
        ),
        migrations.DeleteModel(
            name='hall',
        ),
        migrations.AddField(
            model_name='bookedseats',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seats.seat'),
        ),
    ]
