# Generated by Django 4.1 on 2022-08-15 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('seats', '0005_bookedseats_remove_seat_hall_seat_price_delete_hall_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookedseats',
            new_name='bookedseat',
        ),
    ]
