# Generated by Django 4.1 on 2022-08-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seats', '0006_rename_bookedseats_bookedseat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='customer',
        ),
        migrations.AddField(
            model_name='bookedseat',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
