# Generated by Django 4.1 on 2022-08-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255)),
                ('banner', models.ImageField(null=True, upload_to='media/movies/')),
                ('trailer', models.URLField(max_length=255, null=True)),
                ('genre', models.CharField(max_length=20)),
                ('synposis', models.TextField()),
                ('production', models.CharField(max_length=40)),
                ('producer', models.CharField(max_length=40)),
                ('director', models.CharField(max_length=40)),
                ('released_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
